-- stock_tracker.sql
-- Run this in Supabase SQL Editor after deployment.

create extension if not exists pgcrypto;

create table if not exists public.watchlist (
  id bigint generated by default as identity primary key,
  symbol text not null,
  "addedAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public.stock_data (
  id bigint generated by default as identity primary key,
  symbol text not null,
  date text not null,
  open text not null,
  high text not null,
  low text not null,
  close text not null,
  volume text not null,
  "cachedAt" timestamptz not null default now()
);

create table if not exists public.analysis_cache (
  id bigint generated by default as identity primary key,
  "userId" bigint not null,
  symbol text not null,
  "analysisType" text not null,
  result text not null,
  "createdAt" timestamptz not null default now()
);

create index if not exists idx_watchlist_symbol on public.watchlist(symbol);
create index if not exists idx_stock_data_symbol on public.stock_data(symbol);
create index if not exists idx_analysis_cache_user_symbol on public.analysis_cache("userId", symbol);
